### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by mmarcelofrm** [Drumber/RemoteLight#6] opened 2020-07-28 22:27 UTC
This issue was automatically created by the RemoteLight ExceptionHandler.
RemoteLightCore version: v0.2.2
OS: Windows 10
StackTrace:
```
java.lang.NullPointerException
	at de.lars.remotelightcore.devices.arduino.ComPort.openPort(ComPort.java:84)
	at de.lars.remotelightcore.devices.arduino.Arduino.connect(Arduino.java:69)
	at de.lars.remotelightcore.devices.Device.onActivate(Device.java:78)
	at de.lars.remotelightcore.out.OutputManager.activate(OutputManager.java:90)
	at de.lars.remotelightcore.out.OutputManager.setActiveOutput(OutputManager.java:78)
	at de.lars.remotelightcore.SetupHelper$1.run(SetupHelper.java:114)
	at java.lang.Thread.run(Unknown Source)

```
*Jul 28, 2020 6:25 PM*

**Comment by Drumber** [comment] 2020-07-29 14:41
Duplicate of #5 , but thanks for reporting anyway.
Release with fix will be released very soon.

**Closed by Drumber** 2020-07-29 14:41 UTC
Labels: duplicate
